let data = [
    {
    "id": 351286,
    "poster_path": "/c9XxwwhPHdaImA2f1WEfEsbhaFB.jpg",
    "original_title": "Jurassic World: Fallen Kingdom",
    "overview": "Several years after the demise of Jurassic World, a volcanic eruption threatens the remaining dinosaurs on the island of Isla Nublar. Claire Dearing, the former park manager and founder of the Dinosaur Protection Group, recruits Owen Grady to help prevent the extinction of the dinosaurs once again.",
    "release_date": "2018-06-06",
    "thoughtProvoking": 45,
	"uplifting": 47,
	"light": 122,
	"tearJerker": 46,
	"challenging": 1,
	"despair": 68
  },
  {
    "id": 363088,
    "poster_path": "/rv1AWImgx386ULjcf62VYaW8zSt.jpg",
    "original_title": "Ant-Man and the Wasp",
    "overview": "As Scott Lang awaits expiration of his term of house detention, Hope van Dyne and Dr. Hank Pym involve him in a scheme to rescue Mrs. van Dyne from the micro-universe into which she has fallen, while two groups of schemers converge on them with intentions of stealing Dr. Pym's inventions.",
    "release_date": "2018-07-04",
    "thoughtProvoking": 103,
	"uplifting": 89,
	"nostalgic": 55,
	"powerful": 48,
	"despair": 76
  },
  {
    "id": 284053,
    "poster_path": "/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
    "original_title": "Thor: Ragnarok",
    "overview": "Thor is on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the prophecy of destruction to his homeworld and the end of Asgardian civilization, at the hands of an all-powerful new threat, the ruthless Hela.",
    "release_date": "2017-10-25",
	"tearJerker": 45,
	"challenging": 28,
	"powerful": 88,
	"despair": 44
  },
  {
    "id": 299536,
    "poster_path": "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    "original_title": "Avengers: Infinity War",
    "overview": "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
    "release_date": "2018-04-25",
    "thoughtProvoking": 555,
	"uplifting": 434,
	"nostalgic": 223,
	"powerful": 745,
	"despair": 648
  },
  {
    "id": 260513,
    "poster_path": "/x1txcDXkcM65gl7w20PwYSxAYah.jpg",
    "original_title": "Incredibles 2",
    "overview": "Elastigirl springs into action to save the day, while Mr. Incredible faces his greatest challenge yet – taking care of the problems of his three children.",
    "release_date": "2018-06-14",
	"despair": 856
  },
  {
    "id": 427641,
    "poster_path": "/3gIO6mCd4Q4PF1tuwcyI3sjFrtI.jpg",
    "original_title": "Rampage",
    "overview": "Primatologist Davis Okoye shares an unshakable bond with George, the extraordinarily intelligent, silverback gorilla who has been in his care since birth.  But a rogue genetic experiment gone awry mutates this gentle ape into a raging creature of enormous size.  To make matters worse, it’s soon discovered there are other similarly altered animals.  As these newly created alpha predators tear across North America, destroying everything in their path, Okoye teams with a discredited genetic engineer to secure an antidote, fighting his way through an ever-changing battlefield, not only to halt a global catastrophe but to save the fearsome creature that was once his friend.",
    "release_date": "2018-04-12",
    "thoughtProvoking": 15,
	"uplifting": 84,
	"light": 312,
	"tearJerker": 456
  },
  {
    "id": 333339,
    "poster_path": "/pU1ULUq8D3iRxl1fdX2lZIzdHuI.jpg",
    "original_title": "Ready Player One",
    "overview": "When the creator of a popular video game system dies, a virtual contest is created to compete for his fortune.",
    "release_date": "2018-03-28",
    "thoughtProvoking": 155,
	"uplifting": 42,
	"despair": 658
  },
  {
    "id": 337167,
    "poster_path": "/jjPJ4s3DWZZvI4vw8Xfi4Vqa1Q8.jpg",
    "original_title": "Fifty Shades Freed",
    "overview": "Believing they have left behind shadowy figures from their past, newlyweds Christian and Ana fully embrace an inextricable connection and shared life of luxury. But just as she steps into her role as Mrs. Grey and he relaxes into an unfamiliar stability, new threats could jeopardize their happy ending before it even begins.",
    "release_date": "2018-01-17",
    "thoughtProvoking": 48,
	"uplifting": 65,
	"despair": 99
  },
  {
    "id": 353081,
    "poster_path": "/80PWnSTkygi3QWWmJ3hrAwqvLnO.jpg",
    "original_title": "Mission: Impossible - Fallout",
    "overview": "When an IMF mission ends badly, the world is faced with dire consequences. As Ethan Hunt takes it upon himself to fulfil his original briefing, the CIA begin to question his loyalty and his motives. The IMF team find themselves in a race against time, hunted by assassins while trying to prevent a global catastrophe.",
    "release_date": "2018-07-25",
    "thoughtProvoking": 25,
	"light": 192,
	"challenging": 78
  },
  {
    "id": 442249,
    "poster_path": "/2slvblTroiT1lY9bYLK7Amigo1k.jpg",
    "original_title": "The First Purge",
    "overview": "To push the crime rate below one percent for the rest of the year, the New Founding Fathers of America test a sociological theory that vents aggression for one night in one isolated community. But when the violence of oppressors meets the rage of the others, the contagion will explode from the trial-city borders and spread across the nation.",
    "release_date": "2018-07-04",
    "thoughtProvoking": 56,
	"uplifting": 43,
	"light": 122,
	"tearJerker": 16
  },
  {
    "id": 447332,
    "poster_path": "/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
    "original_title": "A Quiet Place",
    "overview": "A family is forced to live in silence while hiding from creatures that hunt by sound.",
    "release_date": "2018-04-03",
	"nostalgic": 213,
	"powerful": 445,
	"despair": 684
  },
  {
    "id": 400155,
    "poster_path": "/gjAFM4xhA5vyLxxKMz38ujlUfDL.jpg",
    "original_title": "Hotel Transylvania 3: Summer Vacation",
    "overview": "Dracula, Mavis, Johnny and the rest of the Drac Pack take a vacation on a luxury Monster Cruise Ship, where Dracula falls in love with the ship's captain, Ericka, who's secretly a descendant of Abraham Van Helsing, the notorious monster slayer.",
    "release_date": "2018-07-12",
    "thoughtProvoking": 511,
	"uplifting": 141,
	"despair": 681
  },
  {
    "id": 102899,
    "poster_path": "/D6e8RJf2qUstnfkTslTXNTUAlT.jpg",
    "original_title": "Ant-Man",
    "overview": "Armed with the astonishing ability to shrink in scale but increase in strength, master thief Scott Lang must embrace his inner-hero and help his mentor, Doctor Hank Pym, protect the secret behind his spectacular Ant-Man suit from a new generation of towering threats. Against seemingly insurmountable obstacles, Pym and Lang must plan and pull off a heist that will save the world.",
    "release_date": "2015-07-14",
    "thoughtProvoking": 52,
	"uplifting": 44,
	"light": 126,
	"tearJerker": 56,
	"challenging": 77,
	"mindScrew": 88
  },
  {
    "id": 447200,
    "poster_path": "/3NL1FiTEhU4SWOuWk8lkVCbmnYm.jpg",
    "original_title": "Skyscraper",
    "overview": "Framed and on the run, a former FBI agent must save his family from a blazing fire in the world's tallest building.",
    "release_date": "2018-07-11",
    "thoughtProvoking": 55,
	"uplifting": 45,
	"light": 142,
	"tearJerker": 46,
	"challenging": 17
  },
  {
    "id": 284054,
    "poster_path": "/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
    "original_title": "Black Panther",
    "overview": "King T'Challa returns home from America to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne by factions within his own country as well as without. Using powers reserved to Wakandan kings, T'Challa assumes the Black Panther mantel to join with girlfriend Nakia, the queen-mother, his princess-kid sister, members of the Dora Milaje (the Wakandan 'special forces') and an American secret agent, to prevent Wakanda from being dragged into a world war.",
    "release_date": "2018-02-13",
	"light": 12,
	"powerful": 45,
	"despair": 68
  },
  {
    "id": 238636,
    "poster_path": "/l1DRl40x2OWUoPP42v8fjKdS1Z3.jpg",
    "original_title": "The Purge: Anarchy",
    "overview": "One night per year, the government sanctions a 12-hour period in which citizens can commit any crime they wish -- including murder -- without fear of punishment or imprisonment. Leo, a sergeant who lost his son, plans a vigilante mission of revenge during the mayhem. However, instead of a death-dealing avenger, he becomes the unexpected protector of four innocent strangers who desperately need his help if they are to survive the night.",
    "release_date": "2014-07-17",
    "thoughtProvoking": 75,
	"uplifting": 74,
	"light": 712,
	"tearJerker": 76
  },
  {
    "id": 383498,
    "popularity": 70.361,
    "poster_path": "/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg",
    "original_title": "Deadpool 2",
    "overview": "Wisecracking mercenary Deadpool battles the evil and powerful Cable and other bad guys to save a boy's life.",
    "release_date": "2018-05-15",
    "thoughtProvoking": 15,
	"uplifting": 14,
	"light": 112,
	"tearJerker": 16,
	"challenging": 71
  },
  {
    "id": 158015,
    "poster_path": "/tGGJOuLHX7UDlTz57sjfhW1qreP.jpg",
    "original_title": "The Purge",
    "overview": "Given the country's overcrowded prisons, the U.S. government begins to allow 12-hour periods of time in which all illegal activity is legal. During one of these free-for-alls, a family must protect themselves from a home invasion.",
    "release_date": "2013-05-31",
    "thoughtProvoking": 5,
	"uplifting": 4,
	"light": 12,
	"tearJerker": 6,
	"challenging": 7,
	"mindScrew": 8,
	"nostalgic": 23,
	"powerful": 45,
	"despair": 68
  }
]